post_install() {
    if [ -x usr/bin/xdg-icon-resource ]; then
      xdg-icon-resource forceupdate --theme hicolor 2> /dev/null
    fi
}

post_upgrade() {
    if [ -x usr/bin/xdg-icon-resource ]; then
      xdg-icon-resource forceupdate --theme hicolor 2> /dev/null
    fi  
}

post_remove() {
    if [ -x usr/bin/xdg-icon-resource ]; then
      xdg-icon-resource forceupdate --theme hicolor 2> /dev/null
    fi
}
