#!/usr/bin/sh

. /etc/rc.d/rc.pidfile

pre_start() {
    /usr/bin/dbus-uuidgen --ensure
    mkdir /run/dbus
    chown messagebus:messagebus /run/dbus
}

respawn
run /usr/bin/dbus-daemon --system --nofork --nopidfile

dispatch_command "${1}"
