=head1 NAME

ntpd - network time protocol client/server

=head1 SYNOPSIS

B<ntpd> [B<-dnqNwl>] [B<-S> I<PROG>] [B<-p> I<PEER>]...

=head1 DESCRIPTION

B<ntpd> has two functions: to synchronize a system's clock with another
machine, and to host a server so that other machines can synchronize with
this system.

=over 4

=item B<-d>

Verbose

=item B<-n>

Do not daemonize

=item B<-q>

Quit after clock is set

=item B<-N>

Run at a high priority

=item B<-w>

Do not set time (only query peers), implies -n

=item B<-l>

Run as server on port 123

=item B<-S> I<PROG>

Run PROG after stepping time, stratum change, and every 11 mins

=item B<-p> I<PEER>

Obtain time from PEER (may be repeated)

=back

=head1 EXAMPLES

=head2 Synchronize

Most users will use the following command to ensure their computer's clock is
accurate:

=over

B<ntpd -nq -p pool.ntp.org>

=back

=head1 AUTHORS

This command is part of the L<BusyBox|http://busybox.net> tool collection.

=cut
