#!/usr/bin/sh

. /etc/rc.d/rc.functions

service_start() {
	daemon -u ntpd \
	       -p /var/run/ntpd.pid \
	       -r \
	       /usr/bin/ntpd -n -p "$(cat /etc/ntpd.conf 2>/dev/null || echo pool.ntp.org)"
}

service_stop() {
    kill_pidfile /var/run/ntpd.pid
}

service_status() {
    status_pidfile /var/run/ntpd.pid
}

service_help() {
    echo "ntpd [start | stop | status]"
}

dispatch_command "${1}"
