#!/usr/bin/sh

. /etc/rc.d/rc.functions

service_start() {
	daemon -p /var/run/openssh.pid \
	       -r \
	       /usr/bin/sshd -D
}

service_stop() {
    stop_pidfile /var/run/openssh.pid
}

service_status() {
    status_pidfile /var/run/openssh.pid
}

service_help() {
	echo "openssh [start | stop | status]"
}

dispatch_command "${1}"
